# -*- coding: utf-8 -*-
"""WHDImporting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RLF3smPqEaqigCXjkZwUupoRu1ztJIX4
"""

!pip install pandas
import pandas as pd

cancer3070 = pd.read_csv("/content/drive/MyDrive/Machine Learning/WorldHealthData/30-70cancerChdEtc.csv")

cleanfuel = pd.read_csv("/content/drive/MyDrive/Machine Learning/WorldHealthData/cleanFuelAndTech.csv")

c_suicide = pd.read_csv("/content/drive/MyDrive/Machine Learning/WorldHealthData/crudeSuicideRates.csv")

avaible_uhc = pd.read_csv("/content/drive/MyDrive/Machine Learning/WorldHealthData/dataAvailibilityForUhc.csv")

dentists = pd.read_csv("/content/drive/MyDrive/Machine Learning/WorldHealthData/dentists.csv")

el_voilence_w = pd.read_csv("/content/drive/MyDrive/Machine Learning/WorldHealthData/eliminateViolenceAgainstWomen.csv")

lifexp_birth = pd.read_csv("/content/drive/MyDrive/Machine Learning/WorldHealthData/HALElifeExpectancyAtBirth.csv")

lifexp_birth_r = pd.read_csv("/content/drive/MyDrive/Machine Learning/WorldHealthData/HALeWHOregionLifeExpectancyAtBirth.csv")

hepB_antigen = pd.read_csv("/content/drive/MyDrive/Machine Learning/WorldHealthData/hepatitusBsurfaceAntigen.csv")